spring:
  application:
    name: PhoneService
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneservice
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  app:
    kaggle:
      url: https://www.kaggle.com/datasets/
      name: abdulmalik1518/mobiles-dataset-2025
  flyway:
    enabled: true
    baseline-on-migrate: true
    validateMigrationNaming: true
